### ISSUE TITLE
OSError importing redbrick with readonly home directory

### ISSUE THREAD

**Issue by andychisholm** [redbrick-ai/redbrick-sdk#148]
For example `import redbrick` when running from a dockerised lambda will produce:
```
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/hai_chexpert/orchestration.py", line 8, in <module>
    import redbrick  # ignore[import]
  File "/var/lang/lib/python3.8/site-packages/redbrick/__init__.py", line 57, in <module>
    version_check(__version__)
  File "/var/lang/lib/python3.8/site-packages/redbrick/version_check.py", line 28, in version_check
    os.makedirs(os.path.dirname(cache_file), exist_ok=True)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
```

(And spits back the more impenetrable message: `Unknown application error occurred Runtime.Unknown`)

More generally:
- I'd say it's unexpected for `import` statement to have side-effects like creating directories/config
- Using a user's home directory (presumably) breaks the isolation you'd expect if e.g. using a virtual environment
    - I'm not sure exactly how that `version` or other `~/.redbrickai` content is used but if I had multiple projects with different version of redbrick locally, I assume it might get spicy!

Using the project or VE root might be an alternative if this really is necessary state to keep around on disk?

**Comment by pritamrungta** [comment]
Thanks for bringing this up @andychisholm 
We're planning to make the config file customizable

Proposed solution for now (that works):
Set the `HOME` env to a writable home path (could be virtualenv root) as - `HOME=/tmp python script.py`
